apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: demo-logging
  name: demo-logging
  namespace: demo-logging
spec:
  selector:
    matchLabels:
      io.kompose.service: demo-logging
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: demo-logging
    spec:
      containers:
        - image: shiddiqfizuhri/demo-logging:latest
          imagePullPolicy: Always
          name: demo-logging
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "400M"
              cpu: "500m"
            requests:
              memory: 400M
              cpu: "400m"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
