apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: demo-logging
  name: demo-logging
  namespace: demo-logging
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    io.kompose.service: demo-logging
  type: LoadBalancer
